on:
  push:
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ["index"]
        os: ["linux", "win"]
    steps:
    - uses: actions/checkout@v1
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: npm install
      run: npm install
    - name: lint
      run: npm run lint
    - name: tsc
      run: npm run build
    - name: pkg
      run: npm run pkg
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}_${{ matrix.os }}
        path: pkg/
        if-no-files-found: error