on:
  push:
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: npm install
      run: npm install
    - name: lint
      run: npm run lint
    - name: tsc
      run: npm run build
    - name: pkg
      run: npm run pkg
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: pkg/index-macos
        if-no-files-found: warn
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: win.exe
        path: pkg/index-win.exe
        if-no-files-found: warn
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: pkg/index-linux
        if-no-files-found: warn